name: Distribution
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:

  demo_distro_ios:
    name: iOS distribution demo
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build for iOS
        run: flutter build ios --release --no-codesign




